# Generated by Django 5.2.8 on 2025-11-14 14:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom en français')),
                ('name_wo', models.CharField(max_length=100, verbose_name='Nom en wolof')),
                ('start_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('end_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('description_fr', models.TextField(blank=True)),
                ('description_wo', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Saison',
                'verbose_name_plural': 'Saisons',
                'ordering': ['start_month'],
            },
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom en français')),
                ('name_wo', models.CharField(max_length=100, verbose_name='Nom en wolof')),
                ('description_fr', models.TextField(verbose_name='Description en français')),
                ('description_wo', models.TextField(verbose_name='Description en wolof')),
                ('ph_min', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('ph_max', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('texture', models.CharField(choices=[('argileuse', 'Argileuse'), ('sableuse', 'Sableuse'), ('limoneuse', 'Limoneuse'), ('mixte', 'Mixte')], max_length=50)),
                ('drainage', models.CharField(choices=[('excellent', 'Excellent'), ('bon', 'Bon'), ('moyen', 'Moyen'), ('faible', 'Faible')], max_length=50)),
                ('fertility', models.CharField(choices=[('très_élevée', 'Très élevée'), ('élevée', 'Élevée'), ('moyenne', 'Moyenne'), ('faible', 'Faible')], max_length=50)),
                ('water_retention', models.CharField(choices=[('très_élevée', 'Très élevée'), ('élevée', 'Élevée'), ('moyenne', 'Moyenne'), ('faible', 'Faible')], max_length=50, verbose_name="Rétention d'eau")),
                ('organic_matter', models.CharField(choices=[('riche', 'Riche'), ('moyen', 'Moyen'), ('pauvre', 'Pauvre')], max_length=50, verbose_name='Matière organique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de sol',
                'verbose_name_plural': 'Types de sol',
                'ordering': ['name_fr'],
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='average_yield',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rendement moyen'),
        ),
        migrations.AddField(
            model_name='crop',
            name='drought_resistant',
            field=models.BooleanField(default=False, verbose_name='Résistant à la sécheresse'),
        ),
        migrations.AddField(
            model_name='crop',
            name='flood_tolerant',
            field=models.BooleanField(default=False, verbose_name='Tolérant aux inondations'),
        ),
        migrations.AddField(
            model_name='crop',
            name='growth_duration_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée du cycle (jours)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='max_altitude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altitude maximale (m)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='max_rainfall',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pluviométrie maximale (mm/an)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='max_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température maximale (°C)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='min_altitude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altitude minimale (m)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='min_rainfall',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pluviométrie minimale (mm/an)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='min_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température minimale (°C)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='optimal_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température optimale (°C)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='plant_spacing_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Espacement entre plants (cm)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='row_spacing_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Espacement entre lignes (cm)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='water_requirement',
            field=models.CharField(choices=[('très_élevé', 'Très élevé'), ('élevé', 'Élevé'), ('moyen', 'Moyen'), ('faible', 'Faible')], default='moyen', max_length=50, verbose_name='Besoin en eau'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.CharField(choices=[('cereales', 'Céréales'), ('legumineuses', 'Légumineuses'), ('legumes', 'Légumes'), ('fruits', 'Fruits'), ('tubercules', 'Tubercules'), ('cultures_rente', 'Cultures de rente'), ('oleagineux', 'Oléagineux'), ('epices', 'Épices et aromates')], max_length=50),
        ),
        migrations.AddField(
            model_name='crop',
            name='suitable_soil_types',
            field=models.ManyToManyField(blank=True, related_name='crops', to='crops.soiltype', verbose_name='Types de sol appropriés'),
        ),
        migrations.CreateModel(
            name='CropSoilRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_preparation_fr', models.TextField(verbose_name='Préparation du sol (FR)')),
                ('soil_preparation_wo', models.TextField(blank=True, verbose_name='Préparation du sol (WO)')),
                ('fertilization_fr', models.TextField(verbose_name='Fertilisation (FR)')),
                ('fertilization_wo', models.TextField(blank=True, verbose_name='Fertilisation (WO)')),
                ('irrigation_fr', models.TextField(verbose_name='Irrigation (FR)')),
                ('irrigation_wo', models.TextField(blank=True, verbose_name='Irrigation (WO)')),
                ('pest_management_fr', models.TextField(verbose_name='Lutte contre maladies/ravageurs (FR)')),
                ('pest_management_wo', models.TextField(blank=True, verbose_name='Lutte contre maladies/ravageurs (WO)')),
                ('harvest_advice_fr', models.TextField(verbose_name='Conseils de récolte (FR)')),
                ('harvest_advice_wo', models.TextField(blank=True, verbose_name='Conseils de récolte (WO)')),
                ('storage_advice_fr', models.TextField(blank=True, verbose_name='Conseils de stockage (FR)')),
                ('storage_advice_wo', models.TextField(blank=True, verbose_name='Conseils de stockage (WO)')),
                ('recommended_amendments_fr', models.TextField(blank=True, verbose_name='Amendements recommandés (FR)')),
                ('recommended_amendments_wo', models.TextField(blank=True, verbose_name='Amendements recommandés (WO)')),
                ('recommended_row_spacing', models.IntegerField(blank=True, null=True, verbose_name='Espacement lignes recommandé (cm)')),
                ('recommended_plant_spacing', models.IntegerField(blank=True, null=True, verbose_name='Espacement plants recommandé (cm)')),
                ('expected_yield', models.CharField(blank=True, max_length=200, verbose_name='Rendement attendu')),
                ('optimal_conditions_fr', models.TextField(blank=True, verbose_name='Conditions optimales (FR)')),
                ('optimal_conditions_wo', models.TextField(blank=True, verbose_name='Conditions optimales (WO)')),
                ('warnings_fr', models.TextField(blank=True, verbose_name='Précautions/Avertissements (FR)')),
                ('warnings_wo', models.TextField(blank=True, verbose_name='Précautions/Avertissements (WO)')),
                ('priority', models.IntegerField(choices=[(1, 'Faible'), (2, 'Normale'), (3, 'Élevée')], default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_recommendations', to='crops.crop')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='crops.season')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_recommendations', to='crops.soiltype')),
            ],
            options={
                'verbose_name': 'Recommandation culture-sol',
                'verbose_name_plural': 'Recommandations culture-sol',
                'ordering': ['-priority', 'crop__name_fr'],
                'unique_together': {('crop', 'soil_type', 'season')},
            },
        ),
    ]
