# Generated by Django 4.2.26 on 2025-11-20 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('buyer_phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('buyer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('buyer_region', models.CharField(max_length=100, verbose_name='Région')),
                ('buyer_village', models.CharField(blank=True, max_length=200, verbose_name='Village/Quartier')),
                ('tool_name', models.CharField(max_length=300, verbose_name="Nom de l'outil")),
                ('tool_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('payment_plan', models.CharField(choices=[('full', 'Paiement unique'), ('2_installments', '2 tranches'), ('3_installments', '3 tranches'), ('4_installments', '4 tranches')], default='full', max_length=20, verbose_name='Plan de paiement')),
                ('message', models.TextField(blank=True, verbose_name='Message/Notes')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('contacted', 'Contacté'), ('confirmed', 'Confirmé'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, verbose_name="Notes de l'admin")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de contact')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_orders', to=settings.AUTH_USER_MODEL, verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': "Commande d'outil",
                'verbose_name_plural': "Commandes d'outils",
                'ordering': ['-created_at'],
            },
        ),
    ]
