# Generated by Django 5.2.8 on 2025-11-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100, verbose_name='Culture')),
                ('region', models.CharField(choices=[('dakar', 'Dakar'), ('thies', 'Thiès'), ('kaolack', 'Kaolack'), ('saint-louis', 'Saint-Louis'), ('ziguinchor', 'Ziguinchor'), ('tambacounda', 'Tambacounda'), ('kolda', 'Kolda'), ('matam', 'Matam'), ('louga', 'Louga'), ('fatick', 'Fatick'), ('diourbel', 'Diourbel'), ('kaffrine', 'Kaffrine'), ('kedougou', 'Kédougou'), ('sedhiou', 'Sédhiou')], max_length=100, verbose_name='Région')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par kg (FCFA)')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('trend', models.CharField(choices=[('up', 'En hausse'), ('down', 'En baisse'), ('stable', 'Stable')], default='stable', max_length=20, verbose_name='Tendance')),
                ('percentage_change', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Changement (%)')),
            ],
            options={
                'verbose_name': 'Prix du marché',
                'verbose_name_plural': 'Prix du marché',
                'ordering': ['-date', 'crop_name', 'region'],
            },
        ),
    ]
