# Generated by Django 4.2.26 on 2025-11-20 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_marketprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('event_type', models.CharField(choices=[('workshop', 'Atelier/Workshop'), ('meeting', 'Rencontre'), ('training', 'Formation'), ('fair', 'Foire agricole'), ('webinar', 'Webinaire')], max_length=50, verbose_name="Type d'événement")),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('location', models.CharField(max_length=300, verbose_name='Lieu')),
                ('region', models.CharField(choices=[('dakar', 'Dakar'), ('thies', 'Thiès'), ('kaolack', 'Kaolack'), ('saint-louis', 'Saint-Louis'), ('ziguinchor', 'Ziguinchor'), ('tambacounda', 'Tambacounda'), ('kolda', 'Kolda'), ('matam', 'Matam'), ('louga', 'Louga'), ('fatick', 'Fatick'), ('diourbel', 'Diourbel'), ('kaffrine', 'Kaffrine'), ('kedougou', 'Kédougou'), ('sedhiou', 'Sédhiou'), ('online', 'En ligne')], max_length=100, verbose_name='Région')),
                ('organizer', models.CharField(max_length=200, verbose_name='Organisateur')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone de contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre max de participants')),
                ('is_free', models.BooleanField(default=True, verbose_name='Gratuit')),
                ('registration_required', models.BooleanField(default=False, verbose_name='Inscription requise')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
