# Generated by Django 5.2.4 on 2025-07-31 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmconnect_app', '0002_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro de téléphone au format +221XXXXXXXXX', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Format: '+221XXXXXXXXX'", regex='\\+?221\\d{9}$')]),
        ),
    ]
