# Generated by Django 5.2.8 on 2025-11-17 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_season_soiltype_crop_average_yield_and_more'),
        ('farmconnect_app', '0003_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(help_text='Ex: Cultures maraîchères, Élevage, Agroforesterie', max_length=200, verbose_name='Spécialisation')),
                ('regions_covered', models.JSONField(default=list, help_text="Liste des régions couvertes par l'agent", verbose_name='Régions couvertes')),
                ('organization', models.CharField(blank=True, help_text="Nom de l'organisation d'origine", max_length=200, verbose_name='Organisation')),
                ('certification', models.CharField(blank=True, help_text='Diplômes et certifications', max_length=200, verbose_name='Certification')),
                ('years_experience', models.IntegerField(default=0, verbose_name="Années d'expérience")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent de vulgarisation',
                'verbose_name_plural': 'Agents de vulgarisation',
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_size', models.DecimalField(decimal_places=2, help_text="Taille de l'exploitation en hectares", max_digits=10, verbose_name="Taille de l'exploitation (ha)")),
                ('region', models.CharField(choices=[('dakar', 'Dakar'), ('thies', 'Thiès'), ('kaolack', 'Kaolack'), ('saint-louis', 'Saint-Louis'), ('ziguinchor', 'Ziguinchor'), ('tambacounda', 'Tambacounda'), ('kolda', 'Kolda'), ('matam', 'Matam'), ('louga', 'Louga'), ('fatick', 'Fatick'), ('diourbel', 'Diourbel'), ('kaffrine', 'Kaffrine'), ('kedougou', 'Kédougou'), ('sedhiou', 'Sédhiou')], max_length=100, verbose_name='Région')),
                ('years_experience', models.IntegerField(default=0, verbose_name="Années d'expérience")),
                ('irrigation_type', models.CharField(choices=[('none', 'Aucune'), ('manual', 'Manuelle'), ('drip', 'Goutte à goutte'), ('sprinkler', 'Aspersion'), ('flood', 'Inondation')], default='none', max_length=50, verbose_name="Type d'irrigation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crops_grown', models.ManyToManyField(related_name='farmers', to='crops.crop', verbose_name='Cultures cultivées')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agriculteur',
                'verbose_name_plural': 'Agriculteurs',
            },
        ),
    ]
