# Generated by Django 5.2.8 on 2025-11-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_location_weatherdata_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'ordering': ['-recorded_at'], 'verbose_name': 'Donnée météorologique', 'verbose_name_plural': 'Données météorologiques'},
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='cloudiness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nébulosité (%)'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='feels_like',
            field=models.FloatField(blank=True, null=True, verbose_name='Ressenti (°C)'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='icon',
            field=models.CharField(blank=True, max_length=10, verbose_name='Icône météo'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Pression (hPa)'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='rain_1h',
            field=models.FloatField(default=0, verbose_name='Pluie dernière heure (mm)'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Enregistré le'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='temp_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Temp. max (°C)'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='temp_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Temp. min (°C)'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='visibility',
            field=models.FloatField(blank=True, null=True, verbose_name='Visibilité (km)'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_direction',
            field=models.IntegerField(blank=True, null=True, verbose_name='Direction du vent (degrés)'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Vitesse du vent (km/h)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.FloatField(verbose_name='Humidité (%)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='Données actuelles'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.FloatField(verbose_name='Température (°C)'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Horodatage'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['region', '-recorded_at'], name='weather_wea_region_a00360_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['is_current', '-recorded_at'], name='weather_wea_is_curr_ec26db_idx'),
        ),
    ]
