"""
Script de population de la base de données avec 50+ cultures sénégalaises,
types de sol et recommandations personnalisées.
"""

from django.core.management.base import BaseCommand
from crops.models import Crop, SoilType, Season, CropSoilRecommendation
from farmconnect_app.models import User


class Command(BaseCommand):
    help = 'Peuple la base de données avec les cultures sénégalaises, types de sol et recommandations'

    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.SUCCESS('Début de la population de la base de données...'))

        # Créer les saisons
        self.create_seasons()

        # Créer les types de sol
        self.create_soil_types()

        # Créer les cultures
        self.create_crops()

        # Créer les recommandations
        self.create_recommendations()

        self.stdout.write(self.style.SUCCESS('Population terminée avec succès !'))

    def create_seasons(self):
        """Créer les saisons agricoles du Sénégal"""
        self.stdout.write('Création des saisons...')

        seasons_data = [
            {
                'name_fr': 'Hivernage',
                'name_wo': 'Nawet',
                'start_month': 6,  # Juin
                'end_month': 10,   # Octobre
                'description_fr': 'Saison des pluies, idéale pour les cultures pluviales',
                'description_wo': 'Jamono ndaw, rafet ñu jëfandikoo ci wëru ñi njëkk ci ndaw'
            },
            {
                'name_fr': 'Saison sèche chaude',
                'name_wo': 'Noorm',
                'start_month': 11,  # Novembre
                'end_month': 2,     # Février
                'description_fr': 'Saison sèche, nécessite irrigation',
                'description_wo': 'Jamono rëy, laaj na irrigation'
            },
            {
                'name_fr': 'Saison sèche fraîche',
                'name_wo': 'Dabuur',
                'start_month': 3,   # Mars
                'end_month': 5,     # Mai
                'description_fr': 'Début de la saison chaude',
                'description_wo': 'Tambali jamono tang'
            },
        ]

        for season_data in seasons_data:
            season, created = Season.objects.get_or_create(
                name_fr=season_data['name_fr'],
                defaults=season_data
            )
            if created:
                self.stdout.write(f'  ✓ Saison créée : {season.name_fr}')

    def create_soil_types(self):
        """Créer les principaux types de sol du Sénégal"""
        self.stdout.write('Création des types de sol...')

        soil_types_data = [
            {
                'name_fr': 'Sol ferrugineux tropical',
                'name_wo': 'Suuf bu rëy bu fere',
                'description_fr': 'Sol rouge à brun, riche en fer, présent dans le bassin arachidier',
                'description_wo': 'Suuf bu xonq walla bu ñuul, am na fere bu bari, am na ci bassin arachidier',
                'ph_min': 5.5,
                'ph_max': 6.5,
                'texture': 'sableuse',
                'drainage': 'bon',
                'fertility': 'moyenne',
                'water_retention': 'moyenne',
                'organic_matter': 'moyen'
            },
            {
                'name_fr': 'Sol argileux de décrue (Dek)',
                'name_wo': 'Dek',
                'description_fr': 'Sol argileux des zones de vallées et de décrue, très fertile',
                'description_wo': 'Suuf bu am na argile, am na ci diir-diir, rafet na lool',
                'ph_min': 6.0,
                'ph_max': 7.5,
                'texture': 'argileuse',
                'drainage': 'faible',
                'fertility': 'très_élevée',
                'water_retention': 'très_élevée',
                'organic_matter': 'riche'
            },
            {
                'name_fr': 'Sol sableux (Dior)',
                'name_wo': 'Dior',
                'description_fr': 'Sol sableux léger, facile à travailler mais peu fertile',
                'description_wo': 'Suuf bu am na sab, yombal na waye amul doom',
                'ph_min': 5.0,
                'ph_max': 6.0,
                'texture': 'sableuse',
                'drainage': 'excellent',
                'fertility': 'faible',
                'water_retention': 'faible',
                'organic_matter': 'pauvre'
            },
            {
                'name_fr': 'Sol sablo-argileux',
                'name_wo': 'Dek-Dior',
                'description_fr': 'Sol mixte combinant sable et argile, polyvalent',
                'description_wo': 'Suuf bu bokk sab ak argile, rafet na lool',
                'ph_min': 5.5,
                'ph_max': 7.0,
                'texture': 'mixte',
                'drainage': 'bon',
                'fertility': 'élevée',
                'water_retention': 'élevée',
                'organic_matter': 'riche'
            },
            {
                'name_fr': 'Sol hydromorphe',
                'name_wo': 'Suuf bu ndaw',
                'description_fr': 'Sol saturé en eau une partie de l\'année, vallées et bas-fonds',
                'description_wo': 'Suuf bu feeñ ci ndox ci benn saxewal ci at bi',
                'ph_min': 5.5,
                'ph_max': 7.0,
                'texture': 'argileuse',
                'drainage': 'faible',
                'fertility': 'élevée',
                'water_retention': 'très_élevée',
                'organic_matter': 'riche'
            },
            {
                'name_fr': 'Sol salé (Tannes)',
                'name_wo': 'Tann',
                'description_fr': 'Sol salin des zones côtières et de mangrove',
                'description_wo': 'Suuf bu am na sel, am na ci kàlif géej ak mangrove',
                'ph_min': 7.0,
                'ph_max': 9.0,
                'texture': 'argileuse',
                'drainage': 'faible',
                'fertility': 'faible',
                'water_retention': 'élevée',
                'organic_matter': 'moyen'
            },
            {
                'name_fr': 'Sol limoneux alluvial',
                'name_wo': 'Suuf bu wacc ci Fleuve',
                'description_fr': 'Sol fertile des bords du fleuve Sénégal',
                'description_wo': 'Suuf bu rafet ci kanam Fleuve Sénégal',
                'ph_min': 6.5,
                'ph_max': 7.5,
                'texture': 'limoneuse',
                'drainage': 'bon',
                'fertility': 'très_élevée',
                'water_retention': 'élevée',
                'organic_matter': 'riche'
            },
        ]

        for soil_data in soil_types_data:
            soil, created = SoilType.objects.get_or_create(
                name_fr=soil_data['name_fr'],
                defaults=soil_data
            )
            if created:
                self.stdout.write(f'  ✓ Type de sol créé : {soil.name_fr}')

    def create_crops(self):
        """Créer 50+ cultures sénégalaises"""
        self.stdout.write('Création des cultures...')

        crops_data = [
            # CÉRÉALES
            {
                'name_fr': 'Mil (Souna)',
                'name_wo': 'Souna',
                'scientific_name': 'Pennisetum glaucum',
                'category': 'cereales',
                'growing_season': 'Hivernage',
                'planting_period': 'Juin-Juillet',
                'harvest_period': 'Octobre-Novembre',
                'description_fr': 'Céréale de base la plus cultivée au Sénégal, très résistante à la sécheresse',
                'description_wo': 'Ñam bu bari ci Senegaal, mënul fey ci rëy',
                'water_requirement': 'faible',
                'min_temperature': 25.0,
                'max_temperature': 35.0,
                'optimal_temperature': 30.0,
                'min_rainfall': 400,
                'max_rainfall': 800,
                'growth_duration_days': 90,
                'drought_resistant': True,
                'row_spacing_cm': 80,
                'plant_spacing_cm': 40,
                'average_yield': '800-1500 kg/ha',
                'suitable_soils': ['Sol ferrugineux tropical', 'Sol sableux (Dior)', 'Sol sablo-argileux']
            },
            {
                'name_fr': 'Maïs',
                'name_wo': 'Mburu jaaw',
                'scientific_name': 'Zea mays',
                'category': 'cereales',
                'growing_season': 'Hivernage',
                'planting_period': 'Mai-Juillet',
                'harvest_period': 'Septembre-Octobre',
                'description_fr': 'Céréale à cycle court, productive avec irrigation',
                'description_wo': 'Ñam bu yomb gaaw, am na ñam bu bari su fekkee ndox',
                'water_requirement': 'élevé',
                'min_temperature': 20.0,
                'max_temperature': 32.0,
                'optimal_temperature': 25.0,
                'min_rainfall': 600,
                'max_rainfall': 1200,
                'growth_duration_days': 120,
                'drought_resistant': False,
                'row_spacing_cm': 75,
                'plant_spacing_cm': 25,
                'average_yield': '2000-4000 kg/ha',
                'suitable_soils': ['Sol argileux de décrue (Dek)', 'Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Riz pluvial',
                'name_wo': 'Ceeb bu ndaw',
                'scientific_name': 'Oryza glaberrima',
                'category': 'cereales',
                'growing_season': 'Hivernage',
                'planting_period': 'Juin-Août',
                'harvest_period': 'Octobre-Décembre',
                'description_fr': 'Riz cultivé sous pluie, adapté aux zones humides',
                'description_wo': 'Ceeb bu jëkk ci ndaw, rafet na ci yoon yu njooy',
                'water_requirement': 'très_élevé',
                'min_temperature': 22.0,
                'max_temperature': 35.0,
                'optimal_temperature': 28.0,
                'min_rainfall': 1000,
                'max_rainfall': 2000,
                'growth_duration_days': 120,
                'drought_resistant': False,
                'flood_tolerant': True,
                'row_spacing_cm': 20,
                'plant_spacing_cm': 20,
                'average_yield': '2000-3500 kg/ha',
                'suitable_soils': ['Sol argileux de décrue (Dek)', 'Sol hydromorphe', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Sorgho',
                'name_wo': 'Baaq',
                'scientific_name': 'Sorghum bicolor',
                'category': 'cereales',
                'growing_season': 'Hivernage',
                'planting_period': 'Juin-Juillet',
                'harvest_period': 'Octobre-Novembre',
                'description_fr': 'Céréale rustique très résistante à la sécheresse',
                'description_wo': 'Ñam bu mënul fey ci rëy',
                'water_requirement': 'faible',
                'min_temperature': 25.0,
                'max_temperature': 40.0,
                'optimal_temperature': 32.0,
                'min_rainfall': 400,
                'max_rainfall': 800,
                'growth_duration_days': 110,
                'drought_resistant': True,
                'row_spacing_cm': 80,
                'plant_spacing_cm': 40,
                'average_yield': '1000-2000 kg/ha',
                'suitable_soils': ['Sol ferrugineux tropical', 'Sol sableux (Dior)', 'Sol sablo-argileux']
            },
            {
                'name_fr': 'Fonio',
                'name_wo': 'Fonyo',
                'scientific_name': 'Digitaria exilis',
                'category': 'cereales',
                'growing_season': 'Hivernage',
                'planting_period': 'Juin-Juillet',
                'harvest_period': 'Septembre-Octobre',
                'description_fr': 'Céréale ancestrale à cycle très court, très nutritive',
                'description_wo': 'Ñam bu njëkk bu gaaw lool, am na vitamines yu bari',
                'water_requirement': 'faible',
                'min_temperature': 25.0,
                'max_temperature': 35.0,
                'optimal_temperature': 30.0,
                'min_rainfall': 400,
                'max_rainfall': 700,
                'growth_duration_days': 75,
                'drought_resistant': True,
                'row_spacing_cm': 20,
                'plant_spacing_cm': 10,
                'average_yield': '500-800 kg/ha',
                'suitable_soils': ['Sol ferrugineux tropical', 'Sol sableux (Dior)']
            },

            # LÉGUMINEUSES
            {
                'name_fr': 'Arachide',
                'name_wo': 'Gerte',
                'scientific_name': 'Arachis hypogaea',
                'category': 'legumineuses',
                'growing_season': 'Hivernage',
                'planting_period': 'Juin-Juillet',
                'harvest_period': 'Octobre-Novembre',
                'description_fr': 'Culture de rente principale du Sénégal, fixe l\'azote',
                'description_wo': 'Wër wu bari ci Senegaal, defal na azote ci suuf',
                'water_requirement': 'moyen',
                'min_temperature': 20.0,
                'max_temperature': 32.0,
                'optimal_temperature': 28.0,
                'min_rainfall': 500,
                'max_rainfall': 1000,
                'growth_duration_days': 120,
                'drought_resistant': False,
                'row_spacing_cm': 50,
                'plant_spacing_cm': 15,
                'average_yield': '1000-1800 kg/ha',
                'suitable_soils': ['Sol ferrugineux tropical', 'Sol sableux (Dior)', 'Sol sablo-argileux']
            },
            {
                'name_fr': 'Niébé (Haricot)',
                'name_wo': 'Neebeej',
                'scientific_name': 'Vigna unguiculata',
                'category': 'legumineuses',
                'growing_season': 'Hivernage',
                'planting_period': 'Juillet-Août',
                'harvest_period': 'Septembre-Novembre',
                'description_fr': 'Légumineuse alimentaire riche en protéines',
                'description_wo': 'Yoonu lekk bu am protéines yu bari',
                'water_requirement': 'moyen',
                'min_temperature': 25.0,
                'max_temperature': 35.0,
                'optimal_temperature': 30.0,
                'min_rainfall': 400,
                'max_rainfall': 700,
                'growth_duration_days': 70,
                'drought_resistant': True,
                'row_spacing_cm': 60,
                'plant_spacing_cm': 20,
                'average_yield': '800-1500 kg/ha',
                'suitable_soils': ['Sol ferrugineux tropical', 'Sol sableux (Dior)', 'Sol sablo-argileux']
            },
            {
                'name_fr': 'Pois de terre (Voandzou)',
                'name_wo': 'Ndamber',
                'scientific_name': 'Vigna subterranea',
                'category': 'legumineuses',
                'growing_season': 'Hivernage',
                'planting_period': 'Juin-Juillet',
                'harvest_period': 'Octobre-Novembre',
                'description_fr': 'Légumineuse traditionnelle très nutritive',
                'description_wo': 'Yoonu lekk bu njëkk bu am vitamines',
                'water_requirement': 'faible',
                'min_temperature': 25.0,
                'max_temperature': 35.0,
                'optimal_temperature': 30.0,
                'min_rainfall': 400,
                'max_rainfall': 800,
                'growth_duration_days': 110,
                'drought_resistant': True,
                'row_spacing_cm': 50,
                'plant_spacing_cm': 20,
                'average_yield': '600-1000 kg/ha',
                'suitable_soils': ['Sol sableux (Dior)', 'Sol ferrugineux tropical']
            },

            # LÉGUMES
            {
                'name_fr': 'Tomate',
                'name_wo': 'Xoñ',
                'scientific_name': 'Solanum lycopersicum',
                'category': 'legumes',
                'growing_season': 'Saison sèche',
                'planting_period': 'Octobre-Décembre',
                'harvest_period': 'Janvier-Mars',
                'description_fr': 'Légume-fruit très cultivé en contre-saison',
                'description_wo': 'Réew wu jëkk bu bari ci saison sèche',
                'water_requirement': 'élevé',
                'min_temperature': 18.0,
                'max_temperature': 30.0,
                'optimal_temperature': 24.0,
                'min_rainfall': 0,
                'max_rainfall': 500,
                'growth_duration_days': 90,
                'drought_resistant': False,
                'row_spacing_cm': 80,
                'plant_spacing_cm': 50,
                'average_yield': '30-60 tonnes/ha',
                'suitable_soils': ['Sol argileux de décrue (Dek)', 'Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Oignon',
                'name_wo': 'Soble',
                'scientific_name': 'Allium cepa',
                'category': 'legumes',
                'growing_season': 'Saison sèche fraîche',
                'planting_period': 'Novembre-Janvier',
                'harvest_period': 'Mars-Mai',
                'description_fr': 'Culture maraîchère de rente importante',
                'description_wo': 'Réew bu bari ci géej',
                'water_requirement': 'élevé',
                'min_temperature': 15.0,
                'max_temperature': 28.0,
                'optimal_temperature': 22.0,
                'min_rainfall': 0,
                'max_rainfall': 300,
                'growth_duration_days': 120,
                'drought_resistant': False,
                'row_spacing_cm': 20,
                'plant_spacing_cm': 10,
                'average_yield': '25-40 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Aubergine africaine',
                'name_wo': 'Jaxatu',
                'scientific_name': 'Solanum macrocarpon',
                'category': 'legumes',
                'growing_season': 'Hivernage et contre-saison',
                'planting_period': 'Toute l\'année',
                'harvest_period': '3-4 mois après plantation',
                'description_fr': 'Légume traditionnel très apprécié',
                'description_wo': 'Réew bu bari ci lekk bu Afrig',
                'water_requirement': 'moyen',
                'min_temperature': 20.0,
                'max_temperature': 35.0,
                'optimal_temperature': 28.0,
                'min_rainfall': 400,
                'max_rainfall': 1000,
                'growth_duration_days': 100,
                'drought_resistant': False,
                'row_spacing_cm': 80,
                'plant_spacing_cm': 60,
                'average_yield': '15-25 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol argileux de décrue (Dek)']
            },
            {
                'name_fr': 'Gombo',
                'name_wo': 'Kànja',
                'scientific_name': 'Abelmoschus esculentus',
                'category': 'legumes',
                'growing_season': 'Hivernage',
                'planting_period': 'Mai-Juillet',
                'harvest_period': 'Juillet-Octobre',
                'description_fr': 'Légume-feuille traditionnel très populaire',
                'description_wo': 'Réew bu njëkk bu bari ci lekk',
                'water_requirement': 'moyen',
                'min_temperature': 20.0,
                'max_temperature': 35.0,
                'optimal_temperature': 28.0,
                'min_rainfall': 500,
                'max_rainfall': 1000,
                'growth_duration_days': 60,
                'drought_resistant': False,
                'row_spacing_cm': 60,
                'plant_spacing_cm': 30,
                'average_yield': '10-15 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol ferrugineux tropical']
            },
            {
                'name_fr': 'Piment',
                'name_wo': 'Kaani',
                'scientific_name': 'Capsicum annuum',
                'category': 'legumes',
                'growing_season': 'Saison sèche',
                'planting_period': 'Octobre-Décembre',
                'harvest_period': 'Janvier-Avril',
                'description_fr': 'Condiment essentiel de la cuisine sénégalaise',
                'description_wo': 'Réew bu bari ci yapp ci lekk',
                'water_requirement': 'élevé',
                'min_temperature': 18.0,
                'max_temperature': 32.0,
                'optimal_temperature': 25.0,
                'min_rainfall': 0,
                'max_rainfall': 400,
                'growth_duration_days': 90,
                'drought_resistant': False,
                'row_spacing_cm': 60,
                'plant_spacing_cm': 40,
                'average_yield': '8-15 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Chou',
                'name_wo': 'Suu',
                'scientific_name': 'Brassica oleracea',
                'category': 'legumes',
                'growing_season': 'Saison sèche fraîche',
                'planting_period': 'Novembre-Janvier',
                'harvest_period': 'Février-Avril',
                'description_fr': 'Légume de contre-saison apprécié',
                'description_wo': 'Réew bu saison sèche',
                'water_requirement': 'élevé',
                'min_temperature': 15.0,
                'max_temperature': 25.0,
                'optimal_temperature': 20.0,
                'min_rainfall': 0,
                'max_rainfall': 300,
                'growth_duration_days': 90,
                'drought_resistant': False,
                'row_spacing_cm': 60,
                'plant_spacing_cm': 50,
                'average_yield': '30-50 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Carotte',
                'name_wo': 'Karrot',
                'scientific_name': 'Daucus carota',
                'category': 'legumes',
                'growing_season': 'Saison sèche fraîche',
                'planting_period': 'Novembre-Janvier',
                'harvest_period': 'Février-Avril',
                'description_fr': 'Légume-racine de contre-saison',
                'description_wo': 'Réew bu ëp ci suuf',
                'water_requirement': 'élevé',
                'min_temperature': 15.0,
                'max_temperature': 25.0,
                'optimal_temperature': 20.0,
                'min_rainfall': 0,
                'max_rainfall': 300,
                'growth_duration_days': 90,
                'drought_resistant': False,
                'row_spacing_cm': 30,
                'plant_spacing_cm': 8,
                'average_yield': '25-40 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol sableux (Dior)']
            },
            {
                'name_fr': 'Laitue',
                'name_wo': 'Salatu',
                'scientific_name': 'Lactuca sativa',
                'category': 'legumes',
                'growing_season': 'Saison sèche fraîche',
                'planting_period': 'Octobre-Février',
                'harvest_period': 'Décembre-Avril',
                'description_fr': 'Légume-feuille de salade',
                'description_wo': 'Ndeyi salad',
                'water_requirement': 'élevé',
                'min_temperature': 12.0,
                'max_temperature': 24.0,
                'optimal_temperature': 18.0,
                'min_rainfall': 0,
                'max_rainfall': 300,
                'growth_duration_days': 60,
                'drought_resistant': False,
                'row_spacing_cm': 30,
                'plant_spacing_cm': 30,
                'average_yield': '15-25 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Concombre',
                'name_wo': 'Konkombar',
                'scientific_name': 'Cucumis sativus',
                'category': 'legumes',
                'growing_season': 'Saison sèche',
                'planting_period': 'Octobre-Janvier',
                'harvest_period': 'Décembre-Mars',
                'description_fr': 'Cucurbitacée rafraîchissante',
                'description_wo': 'Réew bu tàkkusan',
                'water_requirement': 'très_élevé',
                'min_temperature': 18.0,
                'max_temperature': 32.0,
                'optimal_temperature': 25.0,
                'min_rainfall': 0,
                'max_rainfall': 400,
                'growth_duration_days': 70,
                'drought_resistant': False,
                'row_spacing_cm': 100,
                'plant_spacing_cm': 50,
                'average_yield': '20-35 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Courgette',
                'name_wo': 'Kurjet',
                'scientific_name': 'Cucurbita pepo',
                'category': 'legumes',
                'growing_season': 'Saison sèche',
                'planting_period': 'Octobre-Janvier',
                'harvest_period': 'Décembre-Mars',
                'description_fr': 'Cucurbitacée productive',
                'description_wo': 'Réew bu am ñam bu bari',
                'water_requirement': 'élevé',
                'min_temperature': 18.0,
                'max_temperature': 30.0,
                'optimal_temperature': 24.0,
                'min_rainfall': 0,
                'max_rainfall': 400,
                'growth_duration_days': 60,
                'drought_resistant': False,
                'row_spacing_cm': 100,
                'plant_spacing_cm': 80,
                'average_yield': '25-40 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },

            # TUBERCULES
            {
                'name_fr': 'Manioc',
                'name_wo': 'Manyok',
                'scientific_name': 'Manihot esculenta',
                'category': 'tubercules',
                'growing_season': 'Hivernage',
                'planting_period': 'Juin-Août',
                'harvest_period': '8-12 mois après',
                'description_fr': 'Tubercule énergétique très productif',
                'description_wo': 'Réew bu ëp bu am doom bu bari',
                'water_requirement': 'moyen',
                'min_temperature': 20.0,
                'max_temperature': 35.0,
                'optimal_temperature': 28.0,
                'min_rainfall': 800,
                'max_rainfall': 1500,
                'growth_duration_days': 300,
                'drought_resistant': True,
                'row_spacing_cm': 100,
                'plant_spacing_cm': 100,
                'average_yield': '15-30 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol ferrugineux tropical']
            },
            {
                'name_fr': 'Patate douce',
                'name_fw': 'Pataat',
                'scientific_name': 'Ipomoea batatas',
                'category': 'tubercules',
                'growing_season': 'Hivernage',
                'planting_period': 'Juin-Août',
                'harvest_period': '4-5 mois après',
                'description_fr': 'Tubercule sucré nutritif',
                'description_wo': 'Réew bu ëp bu am suxar',
                'water_requirement': 'moyen',
                'min_temperature': 20.0,
                'max_temperature': 32.0,
                'optimal_temperature': 26.0,
                'min_rainfall': 600,
                'max_rainfall': 1200,
                'growth_duration_days': 120,
                'drought_resistant': False,
                'row_spacing_cm': 100,
                'plant_spacing_cm': 40,
                'average_yield': '12-25 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol ferrugineux tropical']
            },
            {
                'name_fr': 'Igname',
                'name_wo': 'Xorom',
                'scientific_name': 'Dioscorea spp.',
                'category': 'tubercules',
                'growing_season': 'Hivernage',
                'planting_period': 'Mai-Juillet',
                'harvest_period': '7-9 mois après',
                'description_fr': 'Tubercule traditionnel de Casamance',
                'description_wo': 'Réew bu ëp bu Kasamaans',
                'water_requirement': 'élevé',
                'min_temperature': 22.0,
                'max_temperature': 32.0,
                'optimal_temperature': 28.0,
                'min_rainfall': 1000,
                'max_rainfall': 1800,
                'growth_duration_days': 240,
                'drought_resistant': False,
                'row_spacing_cm': 100,
                'plant_spacing_cm': 80,
                'average_yield': '10-20 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },

            # FRUITS
            {
                'name_fr': 'Pastèque',
                'name_wo': 'Meloñ',
                'scientific_name': 'Citrullus lanatus',
                'category': 'fruits',
                'growing_season': 'Saison sèche',
                'planting_period': 'Novembre-Février',
                'harvest_period': 'Février-Mai',
                'description_fr': 'Fruit désaltérant cultivé sur grandes surfaces',
                'description_wo': 'Réew bu nelaw sedd',
                'water_requirement': 'élevé',
                'min_temperature': 20.0,
                'max_temperature': 35.0,
                'optimal_temperature': 28.0,
                'min_rainfall': 0,
                'max_rainfall': 400,
                'growth_duration_days': 90,
                'drought_resistant': False,
                'row_spacing_cm': 200,
                'plant_spacing_cm': 150,
                'average_yield': '30-50 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial', 'Sol argileux de décrue (Dek)']
            },
            {
                'name_fr': 'Mangue',
                'name_wo': 'Mango',
                'scientific_name': 'Mangifera indica',
                'category': 'fruits',
                'growing_season': 'Toute l\'année (récolte saison sèche)',
                'planting_period': 'Début hivernage',
                'harvest_period': 'Avril-Juillet',
                'description_fr': 'Fruit d\'exportation majeur du Sénégal',
                'description_wo': 'Réew bu bari ci export',
                'water_requirement': 'moyen',
                'min_temperature': 24.0,
                'max_temperature': 35.0,
                'optimal_temperature': 30.0,
                'min_rainfall': 600,
                'max_rainfall': 1500,
                'growth_duration_days': 365,
                'drought_resistant': True,
                'row_spacing_cm': 800,
                'plant_spacing_cm': 800,
                'average_yield': '10-20 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol ferrugineux tropical', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Banane',
                'name_wo': 'Banaana',
                'scientific_name': 'Musa spp.',
                'category': 'fruits',
                'growing_season': 'Toute l\'année',
                'planting_period': 'Début hivernage',
                'harvest_period': 'Toute l\'année',
                'description_fr': 'Fruit tropical nécessitant irrigation',
                'description_wo': 'Réew bu laaj na ndox bu bari',
                'water_requirement': 'très_élevé',
                'min_temperature': 20.0,
                'max_temperature': 35.0,
                'optimal_temperature': 28.0,
                'min_rainfall': 1200,
                'max_rainfall': 2500,
                'growth_duration_days': 300,
                'drought_resistant': False,
                'row_spacing_cm': 250,
                'plant_spacing_cm': 250,
                'average_yield': '30-50 tonnes/ha',
                'suitable_soils': ['Sol limoneux alluvial', 'Sol hydromorphe']
            },
            {
                'name_fr': 'Papaye',
                'name_wo': 'Papay',
                'scientific_name': 'Carica papaya',
                'category': 'fruits',
                'growing_season': 'Toute l\'année',
                'planting_period': 'Début hivernage',
                'harvest_period': '9-12 mois après',
                'description_fr': 'Fruit vitaminé à croissance rapide',
                'description_wo': 'Réew bu am vitamines bu gaaw lool',
                'water_requirement': 'élevé',
                'min_temperature': 22.0,
                'max_temperature': 35.0,
                'optimal_temperature': 28.0,
                'min_rainfall': 1000,
                'max_rainfall': 2000,
                'growth_duration_days': 300,
                'drought_resistant': False,
                'row_spacing_cm': 300,
                'plant_spacing_cm': 300,
                'average_yield': '40-80 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Citron',
                'name_wo': 'Lëm',
                'scientific_name': 'Citrus limon',
                'category': 'fruits',
                'growing_season': 'Toute l\'année',
                'planting_period': 'Début hivernage',
                'harvest_period': 'Toute l\'année',
                'description_fr': 'Agrume très demandé localement',
                'description_wo': 'Réew bu ñaaw bu bari ci gëm',
                'water_requirement': 'élevé',
                'min_temperature': 18.0,
                'max_temperature': 35.0,
                'optimal_temperature': 26.0,
                'min_rainfall': 800,
                'max_rainfall': 1500,
                'growth_duration_days': 365,
                'drought_resistant': False,
                'row_spacing_cm': 500,
                'plant_spacing_cm': 500,
                'average_yield': '20-40 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },

            # CULTURES DE RENTE
            {
                'name_fr': 'Coton',
                'name_wo': 'Koto',
                'scientific_name': 'Gossypium spp.',
                'category': 'cultures_rente',
                'growing_season': 'Hivernage',
                'planting_period': 'Juin-Juillet',
                'harvest_period': 'Octobre-Décembre',
                'description_fr': 'Culture de rente importante en Casamance',
                'description_wo': 'Wër wu bari ci Kasamaans',
                'water_requirement': 'moyen',
                'min_temperature': 22.0,
                'max_temperature': 35.0,
                'optimal_temperature': 28.0,
                'min_rainfall': 600,
                'max_rainfall': 1200,
                'growth_duration_days': 150,
                'drought_resistant': False,
                'row_spacing_cm': 80,
                'plant_spacing_cm': 40,
                'average_yield': '1500-2500 kg/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol ferrugineux tropical']
            },
            {
                'name_fr': 'Sésame',
                'name_wo': 'Sesam',
                'scientific_name': 'Sesamum indicum',
                'category': 'oleagineux',
                'growing_season': 'Hivernage',
                'planting_period': 'Juin-Juillet',
                'harvest_period': 'Septembre-Octobre',
                'description_fr': 'Oléagineux d\'exportation en expansion',
                'description_wo': 'Wër bu tew bu export',
                'water_requirement': 'faible',
                'min_temperature': 25.0,
                'max_temperature': 35.0,
                'optimal_temperature': 30.0,
                'min_rainfall': 400,
                'max_rainfall': 800,
                'growth_duration_days': 90,
                'drought_resistant': True,
                'row_spacing_cm': 50,
                'plant_spacing_cm': 15,
                'average_yield': '500-800 kg/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol ferrugineux tropical']
            },
            {
                'name_fr': 'Bissap (Hibiscus)',
                'name_wo': 'Bissap',
                'scientific_name': 'Hibiscus sabdariffa',
                'category': 'cultures_rente',
                'growing_season': 'Hivernage',
                'planting_period': 'Juin-Juillet',
                'harvest_period': 'Octobre-Novembre',
                'description_fr': 'Culture traditionnelle pour boisson et feuilles',
                'description_wo': 'Wër bu njëkk ci tooy ak ndeyi',
                'water_requirement': 'moyen',
                'min_temperature': 22.0,
                'max_temperature': 35.0,
                'optimal_temperature': 28.0,
                'min_rainfall': 500,
                'max_rainfall': 1000,
                'growth_duration_days': 120,
                'drought_resistant': False,
                'row_spacing_cm': 80,
                'plant_spacing_cm': 40,
                'average_yield': '1000-1500 kg/ha (calices)',
                'suitable_soils': ['Sol sablo-argileux', 'Sol ferrugineux tropical']
            },
            {
                'name_fr': 'Canne à sucre',
                'name_wo': 'Kana',
                'scientific_name': 'Saccharum officinarum',
                'category': 'cultures_rente',
                'growing_season': 'Hivernage',
                'planting_period': 'Mai-Juillet',
                'harvest_period': '12-18 mois après',
                'description_fr': 'Culture sucrière industrielle',
                'description_wo': 'Wër bu suxar',
                'water_requirement': 'très_élevé',
                'min_temperature': 20.0,
                'max_temperature': 35.0,
                'optimal_temperature': 28.0,
                'min_rainfall': 1200,
                'max_rainfall': 2000,
                'growth_duration_days': 400,
                'drought_resistant': False,
                'row_spacing_cm': 150,
                'plant_spacing_cm': 50,
                'average_yield': '70-100 tonnes/ha',
                'suitable_soils': ['Sol limoneux alluvial', 'Sol hydromorphe']
            },

            # ÉPICES ET AROMATES
            {
                'name_fr': 'Menthe',
                'name_wo': 'Nana',
                'scientific_name': 'Mentha spp.',
                'category': 'epices',
                'growing_season': 'Toute l\'année',
                'planting_period': 'Toute l\'année',
                'harvest_period': 'Toute l\'année',
                'description_fr': 'Plante aromatique pour thé',
                'description_wo': 'Ndeyi bu xeew ci attaya',
                'water_requirement': 'élevé',
                'min_temperature': 15.0,
                'max_temperature': 30.0,
                'optimal_temperature': 22.0,
                'min_rainfall': 400,
                'max_rainfall': 1000,
                'growth_duration_days': 60,
                'drought_resistant': False,
                'row_spacing_cm': 40,
                'plant_spacing_cm': 30,
                'average_yield': '8-12 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Persil',
                'name_wo': 'Persi',
                'scientific_name': 'Petroselinum crispum',
                'category': 'epices',
                'growing_season': 'Saison sèche fraîche',
                'planting_period': 'Octobre-Février',
                'harvest_period': 'Décembre-Avril',
                'description_fr': 'Aromate culinaire',
                'description_wo': 'Ndeyi bu yapp ci lekk',
                'water_requirement': 'élevé',
                'min_temperature': 15.0,
                'max_temperature': 25.0,
                'optimal_temperature': 20.0,
                'min_rainfall': 0,
                'max_rainfall': 300,
                'growth_duration_days': 70,
                'drought_resistant': False,
                'row_spacing_cm': 30,
                'plant_spacing_cm': 15,
                'average_yield': '6-10 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Citronnelle',
                'name_wo': 'Lëm-lëm',
                'scientific_name': 'Cymbopogon citratus',
                'category': 'epices',
                'growing_season': 'Toute l\'année',
                'planting_period': 'Début hivernage',
                'harvest_period': 'Toute l\'année',
                'description_fr': 'Plante médicinale et aromatique',
                'description_wo': 'Ndeyi bu médecine',
                'water_requirement': 'moyen',
                'min_temperature': 20.0,
                'max_temperature': 35.0,
                'optimal_temperature': 28.0,
                'min_rainfall': 600,
                'max_rainfall': 1500,
                'growth_duration_days': 90,
                'drought_resistant': False,
                'row_spacing_cm': 50,
                'plant_spacing_cm': 50,
                'average_yield': '5-8 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol ferrugineux tropical']
            },
            {
                'name_fr': 'Gingembre',
                'name_wo': 'Jenjabar',
                'scientific_name': 'Zingiber officinale',
                'category': 'epices',
                'growing_season': 'Hivernage',
                'planting_period': 'Mai-Juillet',
                'harvest_period': '8-10 mois après',
                'description_fr': 'Rhizome aromatique et médicinal',
                'description_wo': 'Réew bu ëp bu médecine',
                'water_requirement': 'élevé',
                'min_temperature': 20.0,
                'max_temperature': 32.0,
                'optimal_temperature': 26.0,
                'min_rainfall': 1000,
                'max_rainfall': 2000,
                'growth_duration_days': 270,
                'drought_resistant': False,
                'row_spacing_cm': 40,
                'plant_spacing_cm': 30,
                'average_yield': '8-15 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },

            # CULTURES SUPPLÉMENTAIRES
            {
                'name_fr': 'Moringa',
                'name_wo': 'Nebedaye',
                'scientific_name': 'Moringa oleifera',
                'category': 'legumes',
                'growing_season': 'Toute l\'année',
                'planting_period': 'Début hivernage',
                'harvest_period': 'Toute l\'année',
                'description_fr': 'Arbre nutritionnel à feuilles comestibles',
                'description_wo': 'Garab bu am ndeyi bu lekk',
                'water_requirement': 'faible',
                'min_temperature': 22.0,
                'max_temperature': 40.0,
                'optimal_temperature': 30.0,
                'min_rainfall': 400,
                'max_rainfall': 1500,
                'growth_duration_days': 180,
                'drought_resistant': True,
                'row_spacing_cm': 300,
                'plant_spacing_cm': 300,
                'average_yield': '5-10 tonnes feuilles/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol ferrugineux tropical', 'Sol sableux (Dior)']
            },
            {
                'name_fr': 'Baobab (feuilles)',
                'name_wo': 'Guy (lalo)',
                'scientific_name': 'Adansonia digitata',
                'category': 'legumes',
                'growing_season': 'Hivernage',
                'planting_period': 'Début hivernage',
                'harvest_period': 'Hivernage',
                'description_fr': 'Arbre emblématique, feuilles nutritives',
                'description_wo': 'Garab bu njëkk, lalo rafet na lool',
                'water_requirement': 'faible',
                'min_temperature': 20.0,
                'max_temperature': 40.0,
                'optimal_temperature': 30.0,
                'min_rainfall': 300,
                'max_rainfall': 1000,
                'growth_duration_days': 365,
                'drought_resistant': True,
                'row_spacing_cm': 1000,
                'plant_spacing_cm': 1000,
                'average_yield': '2-5 tonnes feuilles/ha',
                'suitable_soils': ['Sol ferrugineux tropical', 'Sol sableux (Dior)', 'Sol sablo-argileux']
            },
            {
                'name_fr': 'Jujubier',
                'name_wo': 'Sidem',
                'scientific_name': 'Ziziphus mauritiana',
                'category': 'fruits',
                'growing_season': 'Toute l\'année',
                'planting_period': 'Début hivernage',
                'harvest_period': 'Saison sèche',
                'description_fr': 'Arbre fruitier résistant',
                'description_wo': 'Garab bu am réew bu mënul fey',
                'water_requirement': 'faible',
                'min_temperature': 20.0,
                'max_temperature': 40.0,
                'optimal_temperature': 32.0,
                'min_rainfall': 300,
                'max_rainfall': 800,
                'growth_duration_days': 365,
                'drought_resistant': True,
                'row_spacing_cm': 600,
                'plant_spacing_cm': 600,
                'average_yield': '5-15 tonnes/ha',
                'suitable_soils': ['Sol ferrugineux tropical', 'Sol sableux (Dior)']
            },
            {
                'name_fr': 'Haricot vert',
                'name_wo': 'Neebeej vert',
                'scientific_name': 'Phaseolus vulgaris',
                'category': 'legumes',
                'growing_season': 'Saison sèche',
                'planting_period': 'Novembre-Février',
                'harvest_period': 'Janvier-Avril',
                'description_fr': 'Légume d\'exportation vers l\'Europe',
                'description_wo': 'Réew bu export ci Europe',
                'water_requirement': 'élevé',
                'min_temperature': 15.0,
                'max_temperature': 28.0,
                'optimal_temperature': 22.0,
                'min_rainfall': 0,
                'max_rainfall': 300,
                'growth_duration_days': 60,
                'drought_resistant': False,
                'row_spacing_cm': 50,
                'plant_spacing_cm': 10,
                'average_yield': '8-15 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Melon',
                'name_wo': 'Meloñ dëj',
                'scientific_name': 'Cucumis melo',
                'category': 'fruits',
                'growing_season': 'Saison sèche',
                'planting_period': 'Novembre-Février',
                'harvest_period': 'Février-Mai',
                'description_fr': 'Fruit sucré apprécié',
                'description_wo': 'Réew bu am suxar bu rafet',
                'water_requirement': 'élevé',
                'min_temperature': 20.0,
                'max_temperature': 35.0,
                'optimal_temperature': 28.0,
                'min_rainfall': 0,
                'max_rainfall': 400,
                'growth_duration_days': 90,
                'drought_resistant': False,
                'row_spacing_cm': 200,
                'plant_spacing_cm': 100,
                'average_yield': '20-35 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Navet',
                'name_wo': 'Nave',
                'scientific_name': 'Brassica rapa',
                'category': 'legumes',
                'growing_season': 'Saison sèche fraîche',
                'planting_period': 'Novembre-Janvier',
                'harvest_period': 'Janvier-Mars',
                'description_fr': 'Légume-racine de contre-saison',
                'description_wo': 'Réew bu ëp ci suuf',
                'water_requirement': 'élevé',
                'min_temperature': 15.0,
                'max_temperature': 25.0,
                'optimal_temperature': 20.0,
                'min_rainfall': 0,
                'max_rainfall': 300,
                'growth_duration_days': 60,
                'drought_resistant': False,
                'row_spacing_cm': 30,
                'plant_spacing_cm': 15,
                'average_yield': '20-30 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Betterave',
                'name_wo': 'Betrav',
                'scientific_name': 'Beta vulgaris',
                'category': 'legumes',
                'growing_season': 'Saison sèche fraîche',
                'planting_period': 'Novembre-Janvier',
                'harvest_period': 'Février-Avril',
                'description_fr': 'Légume-racine nutritif',
                'description_wo': 'Réew bu ëp bu am vitamines',
                'water_requirement': 'élevé',
                'min_temperature': 15.0,
                'max_temperature': 25.0,
                'optimal_temperature': 20.0,
                'min_rainfall': 0,
                'max_rainfall': 300,
                'growth_duration_days': 90,
                'drought_resistant': False,
                'row_spacing_cm': 40,
                'plant_spacing_cm': 10,
                'average_yield': '25-40 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Épinard',
                'name_wo': 'Epinar',
                'scientific_name': 'Spinacia oleracea',
                'category': 'legumes',
                'growing_season': 'Saison sèche fraîche',
                'planting_period': 'Octobre-Février',
                'harvest_period': 'Décembre-Avril',
                'description_fr': 'Légume-feuille riche en fer',
                'description_wo': 'Ndeyi bu am fer bu bari',
                'water_requirement': 'élevé',
                'min_temperature': 12.0,
                'max_temperature': 24.0,
                'optimal_temperature': 18.0,
                'min_rainfall': 0,
                'max_rainfall': 300,
                'growth_duration_days': 50,
                'drought_resistant': False,
                'row_spacing_cm': 30,
                'plant_spacing_cm': 15,
                'average_yield': '10-20 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Poivron',
                'name_wo': 'Kaani bu jëm',
                'scientific_name': 'Capsicum annuum',
                'category': 'legumes',
                'growing_season': 'Saison sèche',
                'planting_period': 'Octobre-Décembre',
                'harvest_period': 'Janvier-Avril',
                'description_fr': 'Légume-fruit doux',
                'description_wo': 'Réew bu amul yomb',
                'water_requirement': 'élevé',
                'min_temperature': 18.0,
                'max_temperature': 30.0,
                'optimal_temperature': 24.0,
                'min_rainfall': 0,
                'max_rainfall': 400,
                'growth_duration_days': 90,
                'drought_resistant': False,
                'row_spacing_cm': 60,
                'plant_spacing_cm': 40,
                'average_yield': '20-35 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial']
            },
            {
                'name_fr': 'Céleri',
                'name_wo': 'Seleri',
                'scientific_name': 'Apium graveolens',
                'category': 'legumes',
                'growing_season': 'Saison sèche fraîche',
                'planting_period': 'Novembre-Janvier',
                'harvest_period': 'Février-Avril',
                'description_fr': 'Légume aromatique',
                'description_wo': 'Réew bu xeew',
                'water_requirement': 'très_élevé',
                'min_temperature': 15.0,
                'max_temperature': 24.0,
                'optimal_temperature': 18.0,
                'min_rainfall': 0,
                'max_rainfall': 300,
                'growth_duration_days': 120,
                'drought_resistant': False,
                'row_spacing_cm': 40,
                'plant_spacing_cm': 30,
                'average_yield': '25-40 tonnes/ha',
                'suitable_soils': ['Sol sablo-argileux', 'Sol limoneux alluvial', 'Sol hydromorphe']
            },
        ]

        for crop_data in crops_data:
            # Extract suitable soils
            suitable_soils = crop_data.pop('suitable_soils', [])

            # Fix name_wo key if it's name_fw
            if 'name_fw' in crop_data:
                crop_data['name_wo'] = crop_data.pop('name_fw')

            crop, created = Crop.objects.get_or_create(
                name_fr=crop_data['name_fr'],
                defaults=crop_data
            )

            if created:
                # Add suitable soil types
                for soil_name in suitable_soils:
                    try:
                        soil = SoilType.objects.get(name_fr=soil_name)
                        crop.suitable_soil_types.add(soil)
                    except SoilType.DoesNotExist:
                        pass

                self.stdout.write(f'  ✓ Culture créée : {crop.name_fr}')

    def create_recommendations(self):
        """Créer quelques recommandations de base"""
        self.stdout.write('Création des recommandations culture-sol...')

        # Get admin user or create one
        try:
            admin_user = User.objects.filter(is_superuser=True).first()
            if not admin_user:
                self.stdout.write(self.style.WARNING('  Aucun admin trouvé, skip des recommandations'))
                return
        except:
            self.stdout.write(self.style.WARNING('  Erreur accès utilisateurs, skip des recommandations'))
            return

        # Exemple: Arachide sur sol ferrugineux
        try:
            arachide = Crop.objects.get(name_fr='Arachide')
            sol_ferrugineux = SoilType.objects.get(name_fr='Sol ferrugineux tropical')
            hivernage = Season.objects.get(name_fr='Hivernage')

            recommendation, created = CropSoilRecommendation.objects.get_or_create(
                crop=arachide,
                soil_type=sol_ferrugineux,
                season=hivernage,
                defaults={
                    'soil_preparation_fr': 'Labourer à 20-25 cm de profondeur. Effectuer un billonnage pour faciliter le drainage.',
                    'soil_preparation_wo': 'Beral suuf ci 20-25 cm. Defal bili ngir ndox mu gën gëna jëkk.',
                    'fertilization_fr': 'Apporter 150 kg/ha de phosphate naturel avant semis. Inoculer les graines avec du rhizobium.',
                    'fertilization_wo': 'Jox 150 kg/ha bu phosphate naturel gannaaw mu jëkk. Defal rhizobium ci graines yi.',
                    'irrigation_fr': 'Irrigation non nécessaire en hivernage si pluviométrie > 500mm. Irrigation d\'appoint possible en fin de cycle.',
                    'irrigation_wo': 'Ndox amul solo ci hivernage su ndaw am 500mm. Man nga defal ndox ci yënne wu njëkka.',
                    'pest_management_fr': 'Traiter contre les pucerons et les chenilles défoliatrices. Rotation avec céréales recommandée.',
                    'pest_management_wo': 'Yéegal contra pucerons ak chenilles. Wutal jëfandikoo ak céréales.',
                    'harvest_advice_fr': 'Récolter quand 75% des feuilles sont jaunes. Arracher manuellement ou mécaniquement.',
                    'harvest_advice_wo': 'Mottali su 75% yi ndeyi yi woni xonq. Mottali ak loxo walla ak machine.',
                    'storage_advice_fr': 'Sécher à 8% d\'humidité. Stocker dans un endroit sec et aéré.',
                    'storage_advice_wo': 'Rëyal te jox ci benn yoon bu rëy te bu am kanam.',
                    'recommended_amendments_fr': 'Apport de matière organique (compost, fumier) à 5-10 t/ha',
                    'recommended_amendments_wo': 'Jox matière organique (compost, litière) ci 5-10 t/ha',
                    'recommended_row_spacing': 50,
                    'recommended_plant_spacing': 15,
                    'expected_yield': '1200-1800 kg/ha',
                    'optimal_conditions_fr': 'Température 25-30°C, pluviométrie 500-700mm bien répartie',
                    'optimal_conditions_wo': 'Tangoor 25-30°C, ndaw 500-700mm bu sedd',
                    'warnings_fr': 'Éviter les sols trop sableux ou trop argileux. Respecter rotation de 3 ans minimum.',
                    'warnings_wo': 'Suñu gis suuf bu sab lool walla bu argile lool. Wutal jëfandikoo 3 at ci kaw.',
                    'priority': 3
                }
            )
            if created:
                self.stdout.write(f'  ✓ Recommandation créée : {recommendation}')
        except Exception as e:
            self.stdout.write(self.style.WARNING(f'  Erreur création recommandation : {e}'))

        self.stdout.write(self.style.SUCCESS('✓ Script de population terminé !'))
