# Generated by Django 5.2.8 on 2025-11-17 12:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0003_season_soiltype_crop_average_yield_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_fr', models.CharField(max_length=255, verbose_name='Titre (Français)')),
                ('title_wo', models.CharField(blank=True, max_length=255, verbose_name='Titre (Wolof)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title (English)')),
                ('category', models.CharField(choices=[('pest', 'Ravageurs'), ('disease', 'Maladies'), ('nutrient', 'Nutrition'), ('watering', 'Irrigation'), ('soil', 'Sol'), ('weather', 'Météo'), ('harvest', 'Récolte'), ('storage', 'Stockage'), ('general', 'Général')], max_length=50, verbose_name='Catégorie')),
                ('tags', models.TextField(blank=True, help_text='Tags séparés par des virgules (ex: soil:sandy, season:dry)', verbose_name='Tags')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('wo', 'Wolof'), ('en', 'English')], default='fr', max_length=2, verbose_name='Langue principale')),
                ('stage', models.CharField(choices=[('planting', 'Plantation'), ('growth', 'Croissance'), ('flowering', 'Floraison'), ('fruiting', 'Fructification'), ('harvest', 'Récolte'), ('post_harvest', 'Post-récolte'), ('general', 'Général')], max_length=50, verbose_name='Stade de croissance')),
                ('content_fr', models.TextField(verbose_name='Contenu (Français)')),
                ('content_wo', models.TextField(blank=True, verbose_name='Contenu (Wolof)')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (English)')),
                ('short_description_fr', models.TextField(max_length=500, verbose_name='Description courte (Français)')),
                ('short_description_wo', models.TextField(blank=True, max_length=500, verbose_name='Description courte (Wolof)')),
                ('short_description_en', models.TextField(blank=True, max_length=500, verbose_name='Short description (English)')),
                ('action_steps_fr', models.TextField(blank=True, help_text='Une étape par ligne', verbose_name="Étapes d'action (Français)")),
                ('action_steps_wo', models.TextField(blank=True, help_text='Une étape par ligne', verbose_name="Étapes d'action (Wolof)")),
                ('action_steps_en', models.TextField(blank=True, help_text='One step per line', verbose_name='Action steps (English)')),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='low', max_length=10, verbose_name='Sévérité')),
                ('view_count', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Utile')),
                ('not_helpful_count', models.IntegerField(default=0, verbose_name='Pas utile')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='En vedette')),
                ('priority', models.IntegerField(default=0, help_text='Plus élevé = plus visible', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Priorité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advice_entries', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice_entries', to='crops.crop', verbose_name='Culture')),
            ],
            options={
                'verbose_name': 'Conseil agricole',
                'verbose_name_plural': 'Conseils agricoles',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionTree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_fr', models.CharField(max_length=255, verbose_name='Nom (Français)')),
                ('name_wo', models.CharField(blank=True, max_length=255, verbose_name='Nom (Wolof)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Name (English)')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('wo', 'Wolof'), ('en', 'English')], default='fr', max_length=2, verbose_name='Langue')),
                ('description_fr', models.TextField(verbose_name='Description (Français)')),
                ('description_wo', models.TextField(blank=True, verbose_name='Description (Wolof)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('tree_structure', models.TextField(help_text="Structure JSON de l'arbre de décision", verbose_name="Structure de l'arbre (JSON)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('usage_count', models.IntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_trees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_trees', to='crops.crop', verbose_name='Culture')),
            ],
            options={
                'verbose_name': 'Arbre de décision',
                'verbose_name_plural': 'Arbres de décision',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedAdvice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes personnelles')),
                ('advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='advice.adviceentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_advice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conseil sauvegardé',
                'verbose_name_plural': 'Conseils sauvegardés',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAdviceInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view', 'Vue'), ('save', 'Sauvegardé'), ('helpful', 'Utile'), ('not_helpful', 'Pas utile'), ('share', 'Partagé')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='advice.adviceentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction conseil',
                'verbose_name_plural': 'Interactions conseils',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='adviceentry',
            index=models.Index(fields=['crop', 'category', 'stage'], name='advice_advi_crop_id_976daf_idx'),
        ),
        migrations.AddIndex(
            model_name='adviceentry',
            index=models.Index(fields=['is_active', '-priority'], name='advice_advi_is_acti_b46f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='adviceentry',
            index=models.Index(fields=['-created_at'], name='advice_advi_created_862c94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedadvice',
            unique_together={('user', 'advice')},
        ),
        migrations.AddIndex(
            model_name='useradviceinteraction',
            index=models.Index(fields=['user', '-timestamp'], name='advice_user_user_id_05ca6f_idx'),
        ),
        migrations.AddIndex(
            model_name='useradviceinteraction',
            index=models.Index(fields=['advice', 'action'], name='advice_user_advice__8ce13c_idx'),
        ),
    ]
