# Generated by Django 4.2.26 on 2025-11-17 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crops', '0003_season_soiltype_crop_average_yield_and_more'),
        ('advice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropAdvice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planting_season_fr', models.TextField(help_text='Meilleures périodes pour planter cette culture', verbose_name='Saison de plantation (Français)')),
                ('planting_season_wo', models.TextField(blank=True, verbose_name='Saison de plantation (Wolof)')),
                ('planting_season_en', models.TextField(blank=True, verbose_name='Planting Season (English)')),
                ('maturity_time_fr', models.TextField(help_text="Temps nécessaire pour la culture jusqu'à la récolte", verbose_name='Durée de maturation (Français)')),
                ('maturity_time_wo', models.TextField(blank=True, verbose_name='Durée de maturation (Wolof)')),
                ('maturity_time_en', models.TextField(blank=True, verbose_name='Maturity Time (English)')),
                ('challenges_insects_fr', models.TextField(help_text='Insectes qui attaquent cette culture', verbose_name='Insectes nuisibles (Français)')),
                ('challenges_insects_wo', models.TextField(blank=True, verbose_name='Insectes nuisibles (Wolof)')),
                ('challenges_insects_en', models.TextField(blank=True, verbose_name='Pest Insects (English)')),
                ('challenges_diseases_fr', models.TextField(help_text='Maladies qui affectent cette culture', verbose_name='Maladies courantes (Français)')),
                ('challenges_diseases_wo', models.TextField(blank=True, verbose_name='Maladies courantes (Wolof)')),
                ('challenges_diseases_en', models.TextField(blank=True, verbose_name='Common Diseases (English)')),
                ('challenges_environmental_fr', models.TextField(help_text='Sécheresse, inondations, etc.', verbose_name='Problèmes environnementaux (Français)')),
                ('challenges_environmental_wo', models.TextField(blank=True, verbose_name='Problèmes environnementaux (Wolof)')),
                ('challenges_environmental_en', models.TextField(blank=True, verbose_name='Environmental Issues (English)')),
                ('prevention_tips_fr', models.TextField(help_text='Comment prévenir les problèmes', verbose_name='Conseils de prévention (Français)')),
                ('prevention_tips_wo', models.TextField(blank=True, verbose_name='Conseils de prévention (Wolof)')),
                ('prevention_tips_en', models.TextField(blank=True, verbose_name='Prevention Tips (English)')),
                ('management_tips_fr', models.TextField(help_text='Comment gérer les problèmes existants', verbose_name='Conseils de gestion (Français)')),
                ('management_tips_wo', models.TextField(blank=True, verbose_name='Conseils de gestion (Wolof)')),
                ('management_tips_en', models.TextField(blank=True, verbose_name='Management Tips (English)')),
                ('recommended_fertilizers_fr', models.TextField(help_text="Types et quantités d'engrais", verbose_name='Engrais recommandés (Français)')),
                ('recommended_fertilizers_wo', models.TextField(blank=True, verbose_name='Engrais recommandés (Wolof)')),
                ('recommended_fertilizers_en', models.TextField(blank=True, verbose_name='Recommended Fertilizers (English)')),
                ('recommended_pesticides_fr', models.TextField(help_text='Produits pour contrôler les ravageurs', verbose_name='Pesticides recommandés (Français)')),
                ('recommended_pesticides_wo', models.TextField(blank=True, verbose_name='Pesticides recommandés (Wolof)')),
                ('recommended_pesticides_en', models.TextField(blank=True, verbose_name='Recommended Pesticides (English)')),
                ('recommended_tools_fr', models.TextField(help_text='Outils et équipements nécessaires', verbose_name='Outils recommandés (Français)')),
                ('recommended_tools_wo', models.TextField(blank=True, verbose_name='Outils recommandés (Wolof)')),
                ('recommended_tools_en', models.TextField(blank=True, verbose_name='Recommended Tools (English)')),
                ('innovative_inputs_fr', models.TextField(help_text='Nouvelles techniques et produits pour améliorer le rendement', verbose_name='Intrants innovants (Français)')),
                ('innovative_inputs_wo', models.TextField(blank=True, verbose_name='Intrants innovants (Wolof)')),
                ('innovative_inputs_en', models.TextField(blank=True, verbose_name='Innovative Inputs (English)')),
                ('additional_notes_fr', models.TextField(blank=True, help_text='Autres informations importantes', verbose_name='Notes supplémentaires (Français)')),
                ('additional_notes_wo', models.TextField(blank=True, verbose_name='Notes supplémentaires (Wolof)')),
                ('additional_notes_en', models.TextField(blank=True, verbose_name='Additional Notes (English)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('view_count', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crop_advice', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structured_advice', to='crops.crop', verbose_name='Culture')),
            ],
            options={
                'verbose_name': 'Conseil de culture structuré',
                'verbose_name_plural': 'Conseils de culture structurés',
                'ordering': ['crop__name_fr'],
            },
        ),
    ]
