# Generated by Django 4.2.26 on 2025-11-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0002_cropadvice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropadvice',
            name='soil_type_en',
            field=models.TextField(blank=True, default='', verbose_name='Recommended Soil Types (English)'),
        ),
        migrations.AddField(
            model_name='cropadvice',
            name='soil_type_fr',
            field=models.TextField(default='Tous types de sol adaptés avec bonne préparation', help_text='Types de sol adaptés pour cette culture', verbose_name='Types de sol recommandés (Français)'),
        ),
        migrations.AddField(
            model_name='cropadvice',
            name='soil_type_wo',
            field=models.TextField(blank=True, default='', verbose_name='Types de sol recommandés (Wolof)'),
        ),
    ]
